services:
  mediastore:
    image: sxxxi/mediastore-service:latest
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - portfolio-net

networks:
  portfolio-net:
    external: true
